//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITRAIHSS_BETA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public int Usu_Id { get; set; }
        public string Usu_UserName { get; set; }
        public string Usu_Password { get; set; }
        public bool Usu_Status { get; set; }
        public string Usu_UserCreate { get; set; }
        public Nullable<System.DateTime> Usu_DateCreate { get; set; }
        public string Usu_UserModifies { get; set; }
        public Nullable<System.DateTime> Usu_DateModifies { get; set; }
    }
}
