//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITRAIHSS_BETA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LISTUSER
    {
        public int Id_User { get; set; }
        public string Username { get; set; }
    }
}
